name: reviewdog
on: [pull_request]
jobs:
  stylenlint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.token }}
          reporter: github-pr-review
          stylelint_input: 'src/'